const languages = [
  { label: "English", value: "English" },
  { label: "Spanish", value: "Spanish" },
  { label: "French", value: "French" },
  { label: "Chinese", value: "Chinese" },
  { label: "Hindi", value: "Hindi" },
  { label: "Arabic", value: "Arabic" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Bengali", value: "Bengali" },
  { label: "Russian", value: "Russian" },
  { label: "Japanese", value: "Japanese" },
  { label: "Punjabi", value: "Punjabi" },
  { label: "German", value: "German" },
  { label: "Javanese", value: "Javanese" },
  { label: "Wu Chinese", value: "Wu Chinese" },
  { label: "Malay", value: "Malay" },
  { label: "Telugu", value: "Telugu" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "Korean", value: "Korean" },
  { label: "Turkish", value: "Turkish" },
  { label: "Marathi", value: "Marathi" },
  { label: "Tamil", value: "Tamil" },
  { label: "Urdu", value: "Urdu" },
  { label: "Persian", value: "Persian" },
  { label: "Italian", value: "Italian" },
  { label: "Gujarati", value: "Gujarati" },
  { label: "Polish", value: "Polish" },
  { label: "Ukrainian", value: "Ukrainian" },
  { label: "Romanian", value: "Romanian" },
  { label: "Dutch", value: "Dutch" },
  { label: "Greek", value: "Greek" },
  { label: "Hungarian", value: "Hungarian" },
  { label: "Czech", value: "Czech" },
  { label: "Swedish", value: "Swedish" },
  { label: "Bulgarian", value: "Bulgarian" },
  { label: "Serbian", value: "Serbian" },
  { label: "Danish", value: "Danish" },
  { label: "Finnish", value: "Finnish" },
  { label: "Slovak", value: "Slovak" },
  { label: "Norwegian", value: "Norwegian" },
  { label: "Croatian", value: "Croatian" },
  { label: "Moldovan", value: "Moldovan" },
  { label: "Bosnian", value: "Bosnian" },
  { label: "Albanian", value: "Albanian" },
  { label: "Lithuanian", value: "Lithuanian" },
  { label: "Macedonian", value: "Macedonian" }
];

export default languages;

  